In [1]:
import pyupbit
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pylab import rcParams
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM
from sklearn.preprocessing import MinMaxScaler


In [2]:
df = pyupbit.get_ohlcv("KRW-BTC",count=10000,period=1)
df.head()

open       high        low      close      volume  \
2017-09-25 09:00:00  4201000.0  4333000.0  4175000.0  4322000.0  132.484755   
2017-09-26 09:00:00  4317000.0  4418000.0  4311000.0  4321000.0   22.788340   
2017-09-27 09:00:00  4322000.0  4677000.0  4318000.0  4657000.0   32.269662   
2017-09-28 09:00:00  4657000.0  4772000.0  4519000.0  4586000.0   80.588243   
2017-09-29 09:00:00  4586000.0  4709000.0  4476000.0  4657000.0   59.352373   

                            value  
2017-09-25 09:00:00  5.602146e+08  
2017-09-26 09:00:00  9.950724e+07  
2017-09-27 09:00:00  1.448276e+08  
2017-09-28 09:00:00  3.721860e+08  
2017-09-29 09:00:00  2.724558e+08

In [3]:
df.shape

(1541, 6)

In [11]:
df_1 = pd.DataFrame(df)

df_1

open        high         low       close  \
2017-09-25 09:00:00   4201000.0   4333000.0   4175000.0   4322000.0   
2017-09-26 09:00:00   4317000.0   4418000.0   4311000.0   4321000.0   
2017-09-27 09:00:00   4322000.0   4677000.0   4318000.0   4657000.0   
2017-09-28 09:00:00   4657000.0   4772000.0   4519000.0   4586000.0   
2017-09-29 09:00:00   4586000.0   4709000.0   4476000.0   4657000.0   
...                         ...         ...         ...         ...   
2021-12-09 09:00:00  62217000.0  62499000.0  59200000.0  59425000.0   
2021-12-10 09:00:00  59425000.0  61995000.0  59106000.0  59683000.0   
2021-12-11 09:00:00  59749000.0  61538000.0  59500000.0  61427000.0   
2021-12-12 09:00:00  61414000.0  62887000.0  60904000.0  62049000.0   
2021-12-13 09:00:00  61995000.0  62190000.0  60100000.0  60662000.0   

                          volume         value  
2017-09-25 09:00:00   132.484755  5.602146e+08  
2017-09-26 09:00:00    22.788340  9.950724e+07  
2017-09-27 09:00:00    32.269662  1.448276e+08  
2017-09-28 09:00:00    80.588243  3.721860e+08  
2017-09-29 09:00:00    59.352373  2.724558e+08  
...                          ...           ...  
2021-12-09 09:00:00  6985.125259  4.250350e+11  
2021-12-10 09:00:00  7746.325035  4.660654e+11  
2021-12-11 09:00:00  3629.536770  2.197454e+11  
2021-12-12 09:00:00  3665.345632  2.262398e+11  
2021-12-13 09:00:00  2597.854515  1.583348e+11  

[1541 rows x 6 columns]

In [12]:
df_2=df_1.reset_index()

#print(df)
df_3=df_2.rename(columns={'index':'date'})

df_3

date        open        high         low       close  \
0    2017-09-25 09:00:00   4201000.0   4333000.0   4175000.0   4322000.0   
1    2017-09-26 09:00:00   4317000.0   4418000.0   4311000.0   4321000.0   
2    2017-09-27 09:00:00   4322000.0   4677000.0   4318000.0   4657000.0   
3    2017-09-28 09:00:00   4657000.0   4772000.0   4519000.0   4586000.0   
4    2017-09-29 09:00:00   4586000.0   4709000.0   4476000.0   4657000.0   
...                  ...         ...         ...         ...         ...   
1536 2021-12-09 09:00:00  62217000.0  62499000.0  59200000.0  59425000.0   
1537 2021-12-10 09:00:00  59425000.0  61995000.0  59106000.0  59683000.0   
1538 2021-12-11 09:00:00  59749000.0  61538000.0  59500000.0  61427000.0   
1539 2021-12-12 09:00:00  61414000.0  62887000.0  60904000.0  62049000.0   
1540 2021-12-13 09:00:00  61995000.0  62190000.0  60100000.0  60662000.0   

           volume         value  
0      132.484755  5.602146e+08  
1       22.788340  9.950724e+07  
2       32.269662  1.448276e+08  
3       80.588243  3.721860e+08  
4       59.352373  2.724558e+08  
...           ...           ...  
1536  6985.125259  4.250350e+11  
1537  7746.325035  4.660654e+11  
1538  3629.536770  2.197454e+11  
1539  3665.345632  2.262398e+11  
1540  2597.854515  1.583348e+11  

[1541 rows x 7 columns]

In [15]:
data = df_3.sort_index(ascending=True, axis=0)

new_data = pd.DataFrame(index=range(0,len(df)),columns=['date', 'close'])
# 앞에서 만든 빈 new_data 에 Date, Close만 넣습니다.
#이런식으로 안해도 될텐데...
print(new_data.head())
for i in range(0,len(data)):
    new_data['date'][i] = df_3['date'][i]
    new_data['close'][i] = df_3['close'][i]
print(new_data.head())
new_data
#setting index
#index를 date로 설정합니다.
new_data.index = new_data.date
#그러면 date는 필요없어지니 삭제합니다
new_data.drop('date', axis=1, inplace=True)
print(new_data.head())

  date close
0  NaN   NaN
1  NaN   NaN
2  NaN   NaN
3  NaN   NaN
4  NaN   NaN
                  date      close
0  2017-09-25 09:00:00  4322000.0
1  2017-09-26 09:00:00  4321000.0
2  2017-09-27 09:00:00  4657000.0
3  2017-09-28 09:00:00  4586000.0
4  2017-09-29 09:00:00  4657000.0
                         close
date                          
2017-09-25 09:00:00  4322000.0
2017-09-26 09:00:00  4321000.0
2017-09-27 09:00:00  4657000.0
2017-09-28 09:00:00  4586000.0
2017-09-29 09:00:00  4657000.0


In [16]:
df_3.to_csv('coin2.csv',index=False,encoding='cp949')

In [17]:
# 차트의 기본 크기를 설정합니다. 
rcParams['figure.figsize'] = 8,4 #그림(figure)의 크기. (가로,세로) 인치 단위3
scaler = MinMaxScaler(feature_range=(0, 1))

In [18]:
dataset = df_3.close
dataset_1=np.array(dataset)
dataset_1
dataset_1.shape
#train = dataset_1[0:914,:]
#vaild = dataset_1[914:1217,:]
#test = dataset_1[1217:,:]
print(dataset_1.shape)
print(dataset_1)

(1541,)
[ 4322000.  4321000.  4657000. ... 61427000. 62049000. 60662000.]


In [19]:
print(dataset_1)
a = dataset_1.reshape((-1,1))
print(a.shape)
print(a)

[ 4322000.  4321000.  4657000. ... 61427000. 62049000. 60662000.]
(1541, 1)
[[ 4322000.]
 [ 4321000.]
 [ 4657000.]
 ...
 [61427000.]
 [62049000.]
 [60662000.]]


In [20]:
train = a[0:914,:]
valid = a[914:,:]

In [21]:
print(train.shape)
print(valid.shape)

(914, 1)
(627, 1)


In [22]:
#converting dataset into x_train and y_train
#값을 0 ~ 1 사이의 값으로 변환 합니다
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(a)

x_train, y_train = [], []
for i in range(60,len(train)):
    x_train.append(scaled_data[i-60:i,0])
    y_train.append(scaled_data[i,0])

In [23]:
# x_train [0:60]=>0:59까지데이터 y_train [60]
x_train, y_train = np.array(x_train), np.array(y_train)
#(927, 60) (927,)
# x_train 60깨 input으로 가지는 데이터가 927개 들어있다.
print(x_train.shape,y_train.shape)
print(x_train)

# 입력 format에 맞게 변환 합니다.
x_train = np.reshape(x_train, (x_train.shape[0],x_train.shape[1],1))
print("input_shape")
print(x_train.shape,y_train.shape)
print(x_train)

(854, 60) (854,)
[[0.00903785 0.00902499 0.01334465 ... 0.06845881 0.07025867 0.06844595]
 [0.00902499 0.01334465 0.01243186 ... 0.07025867 0.06844595 0.07168569]
 [0.01334465 0.01243186 0.01334465 ... 0.06844595 0.07168569 0.08047928]
 ...
 [0.07963077 0.07875656 0.08159776 ... 0.05298005 0.04817186 0.05692687]
 [0.07875656 0.08159776 0.08373187 ... 0.04817186 0.05692687 0.06104083]
 [0.08159776 0.08373187 0.08936285 ... 0.05692687 0.06104083 0.05980664]]
input_shape
(854, 60, 1) (854,)
[[[0.00903785]
  [0.00902499]
  [0.01334465]
  ...
  [0.06845881]
  [0.07025867]
  [0.06844595]]

 [[0.00902499]
  [0.01334465]
  [0.01243186]
  ...
  [0.07025867]
  [0.06844595]
  [0.07168569]]

 [[0.01334465]
  [0.01243186]
  [0.01334465]
  ...
  [0.06844595]
  [0.07168569]
  [0.08047928]]

 ...

 [[0.07963077]
  [0.07875656]
  [0.08159776]
  ...
  [0.05298005]
  [0.04817186]
  [0.05692687]]

 [[0.07875656]
  [0.08159776]
  [0.08373187]
  ...
  [0.04817186]
  [0.05692687]
  [0.06104083]]

 [[0.081597

In [24]:
model = Sequential()

model.add(LSTM(units=50, return_sequences=True, input_shape=(x_train.shape[1],1)))
model.add(LSTM(units=50))
model.add(Dense(1))

model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x_train, y_train, epochs=1, batch_size=1, verbose=2)

854/854 - 14s - loss: 3.5420e-04


In [25]:
# 입력 데이터중 마지막 데이터를 가지고 valid 데이터를 만듭니다.
#predicting 246 values, using past 60 from the train data
inputs = new_data[len(new_data) - len(valid) - 60:].values
inputs = inputs.reshape(-1,1)
inputs  = scaler.transform(inputs)

X_test = []
for i in range(60,inputs.shape[0]):
    X_test.append(inputs[i-60:i,0])
X_test = np.array(X_test)

X_test = np.reshape(X_test, (X_test.shape[0],X_test.shape[1],1))

closing_price = model.predict(X_test)
print(closing_price.shape)
closing_price = scaler.inverse_transform(closing_price)
print(closing_price.shape)
print(valid.shape)
rms=np.sqrt(np.mean(np.power((valid-closing_price),2)))
print(rms)

(627, 1)
(627, 1)
(627, 1)
4731937.7449961435


In [27]:
#for plotting
train = new_data[:987]
valid = new_data[987:]
print(train)
print(valid)
valid['Predictions'] = closing_price
plt.plot(train['Close'])
plt.plot(valid[['Close','Predictions']])
plt.show()

                          close
date                           
2017-09-25 09:00:00   4322000.0
2017-09-26 09:00:00   4321000.0
2017-09-27 09:00:00   4657000.0
2017-09-28 09:00:00   4586000.0
2017-09-29 09:00:00   4657000.0
...                         ...
2020-06-03 09:00:00  11648000.0
2020-06-04 09:00:00  11784000.0
2020-06-05 09:00:00  11597000.0
2020-06-06 09:00:00  11641000.0
2020-06-07 09:00:00  11687000.0

[987 rows x 1 columns]
                          close
date                           
2020-06-08 09:00:00  11690000.0
2020-06-09 09:00:00  11688000.0
2020-06-10 09:00:00  11737000.0
2020-06-11 09:00:00  11090000.0
2020-06-12 09:00:00  11380000.0
...                         ...
2021-12-09 09:00:00  59425000.0
2021-12-10 09:00:00  59683000.0
2021-12-11 09:00:00  61427000.0
2021-12-12 09:00:00  62049000.0
2021-12-13 09:00:00  60662000.0

[554 rows x 1 columns]


ValueError: Length of values (627) does not match length of index (554)